language: python

python:
  - "3.4"
  - "3.5"

notifications:
  email: false

install:
  - pip install flask flask-testing coverage

before_script:
  - cd notes
  - sqlite3 ./database.sqlite < ./schema.sql

after_success:
  - coveralls

script:
  - coverage run --source . test_notes.py
