language: python
sudo: required
dist: trusty

python:
  - "3.4"
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt

before_script:
  - cd notes

after_success:
  - coveralls

script:
  - coverage run --source . test_notes.py
