language: python

python:
  - "3.4"
  - "3.5"

notifications:
  email: false

install:
  - pip install flask
  - pip install flask-testing

before_script:
  - cd notes
  - sqlite3 ./database.sqlite < ./schema.sql

script:
  - python ./test_notes.py
