language: python

python:
  - "3.4"
  - "3.5"
  - "pypy"

notifications:
  email: false

install:
  - pip install flask

before_script:
  - cd notes
  - sqlite3 ./database.sqlite < ./schema.sql

script:
  - python ./test_notes.py
